### ISSUE TITLE
Start up and enter recovery automatically

### ISSUE THREAD

**Issue by senseiod** [mastersenpai0405/twrp_xiaomi_chopin#2]
When I input FastBoot reboot, the mobile phone will automatically enter TWRP after power on
Unable to enter the system normally

**Comment by TyraLizQ11** [comment]
Yes sir need to fix

**Comment by mastersenpai05** [comment]
> When I input FastBoot reboot, the mobile phone will automatically enter TWRP after power on Unable to enter the system normally

This tree is not yet stable sir, Need tester for good.

You can contact me at t.me/myusernameiswhat

**Comment by senseiod** [comment]
> > When I input FastBoot reboot, the mobile phone will automatically enter TWRP after power on Unable to enter the system normally
> 
> This tree is not yet stable sir, Need tester for good.
> 
> You can contact me at t.me/myusernameiswhat

I used magiskboot unpack xiaomi's boot.img, and then replaced the compiled ramdisk.cpio.
And use magiskboot repack boot.img
Solved my problem
I hope it can help you build the device tree
Thank you for your device tree

**Comment by mastersenpai05** [comment]
> > > When I input FastBoot reboot, the mobile phone will automatically enter TWRP after power on Unable to enter the system normally
> > 
> > 
> > This tree is not yet stable sir, Need tester for good.
> > You can contact me at t.me/myusernameiswhat
> 
> I used magiskboot unpack xiaomi's boot.img, and then replaced the compiled ramdisk.cpio. And use magiskboot repack boot.img Solved my problem I hope it can help you build the device tree Thank you for your device tree

You can PM me sir. In telegram
